name: Build and Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: apt update
        run: |
          sudo apt-get update

      - name: Install ninja
        run: |
          sudo apt-get install -y ninja-build

      - name: Install gtests
        run: |
          sudo apt-get install -y libgtest-dev

      - name: Install Clang-Tidy
        run: |
          sudo apt-get install -y clang-tidy

      - name: Build
        run: |
          ./build.sh

      - name: Test
        run: |
          ./test

      - name: Clang-Tidy
        run: |
          clang-tidy ./src/**/*.?pp ./tests/*.?pp -p=./build/compile_commands.json --config-file=.clang-tidy
